**Question**-1 : Create a numpy array of **first ten whole numbers** and extract all odd numbers from array

In [ ]:
def create():
  #implement logic here
  pass

**Question-2** : Create a numpy array of **first ten whole numbers** and Convert a 1D array to a 2D array with 2 rows

In [ ]:
def convert():
  #implement logic here
  pass

**Question-3** : Get the common items between a and b

a = [1,2,3,2,3,4,3,4,5,6]

b = [7,2,10,2,7,4,9,4,9,8]

In [ ]:
def common(a,b):
  #implement logic here
  pass

 **Question-4** : Get the positions where elements of a and b match

 a = [1,2,3,2,3,4,3,4,5,6]

b = [7,2,10,2,7,4,9,4,9,8]

In [ ]:
def match(a,b):
  #implement logic here
  pass

**Question-5**: Get all items between 5 and 10 from a.

a = [2, 6, 1, 9, 10, 3, 27]

In [ ]:
def range(a):
  #implement logic here
  pass

**Question-6** : Swap columns 1 and 2 in the array

arr = [[0 1 2]
      [3 4 5]
      [6 7 8]]

In [ ]:
def swap(a):
  #implement logic here
  pass

**Question-7**  : Reverse the rows of a 2D array arr.

arr = [[0 1 2]
      [3 4 5]
      [6 7 8]]

In [ ]:
def reverse(arr):
  #implement logic here
  pass

**Question-8**: Create a 2D array of shape 5x3 to contain random integers between 1 and 100.


In [ ]:
def random():
  #implement logic here
  pass

**Question-9**: Convert the function maxx that works on two scalars, to work on two numpy arrays.

maxx(1, 5) ->Get the maximum of two items

 Output : 5

In [ ]:
def maxx(a,b):
  #implement logic here
  pass

**Question-10**: From array a remove all items present in array b

a = [1,2,3,4,5]

b = [5,6,7,8,9]

In [ ]:
def remove(a,b):
  #implement logic here
  pass